# Site settings
title: "Istruzione e Formazione Tecnica Superiore 2017 @ DISI"
email: danilo.pianini@unibo.it
description: > # this means to ignore newlines until "baseurl:"
  Materiale per il modulo di Sistemi informatici e loro gestione
baseurl: "/ifts2017" # the subpath of your site, e.g. /blog/
url: "http://oop-at-disi.github.io" # the base hostname & protocol for your site
twitter_username: DanySK86
github_username:  danysk
encoding: utf-8

# Build settings
markdown: kramdown
